spring:
  application:
    name: demo-spring-session
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/yugabyte
    username: yugabyte
  security:
    user:
      password: password
  profiles:
    default: jdbc