spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/yugabyte
    username: yugabyte
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      cleanup-cron: "0 */3 * * * *"  # cleans up every 3m (default is every second?)
      #save-mode: always  # 99% = 1,193
      #save-mode: on_set_attribute  # default, 99% = 1,789
    timeout: 60s